version: '3'

services:
  # Define a Telegraf service
  telegraf:
    container_name: host_telegraf
    image: telegraf:1.10.4
    volumes:
    - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
   # - /var/run/docker.sock:/var/run/docker.sock
#    - /sys:/rootfs/sys:ro
#    - /proc:/rootfs/proc:ro
#    - /etc:/rootfs/etc:ro
#    environment:
#       HOST_PROC: /rootfs/proc
#       HOST_SYS: /rootfs/sys
#       HOST_ETC: /rootfs/etc
    ports:
    - "8092:8092/udp"
    - "8094:8094"
    - "8125:8125/udp"