version: '3'

services:
  # Define a Telegraf service
  telegraf:
    container_name: monitor_telegraf
    image: telegraf:1.10.4
    volumes:
    - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
#    - /sys:/rootfs/sys:ro
#    - /proc:/rootfs/proc:ro
#    - /etc:/rootfs/etc:ro
#    environment:
#       HOST_PROC: /rootfs/proc
#       HOST_SYS: /rootfs/sys
#       HOST_ETC: /rootfs/etc
  #  depends_on:
   # - influxdb
    ports:
    - "8092:8092/udp"
    - "8094:8094"
    - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    container_name: monitor_influxdb
    image: influxdb:1.7.6
    volumes:
    - ./data/influxdb:/var/lib/influxdb
    ports:
    - "8086:8086"
  # Define a Chronograf service
  chronograf:
    container_name: monitor_chronograf
    image: chronograf:1.7.11
#    environment:
#      INFLUXDB_URL: http://influxdb:8086
    volumes:
    - ./data/chronograf:/var/lib/chronograf
    ports:
    - "8888:8888"
    depends_on:
    - influxdb